services:
  application:
    image: node:24
    container_name: spherity_coding_challenge
    working_dir: /usr/local/app
    develop:
      watch:
        - path: ./backend/package.json
          action: restart
        - path: ./frontend/package.json
          action: restart
        - path: ./package.json
          action: restart
    volumes:
      - ./:/usr/local/app
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      WALLET_URL: "http://localhost:3000"
      NODE_ENV: "development"
    user: ${USER_ID}
    command: /bin/bash -c "npm install && npm run dev"
