services:
  backend:
    build:
      context: ./
      target: backend-dev
    container_name: spherity_coding_challenge_backend
    develop:
      watch:
        - path: ./backend/package.json
          action: restart
    volumes:
      - ./backend:/usr/local/app
    ports:
      - 3000:3000
    environment:
      WALLET_URL: "http://localhost:3000"
    networks:
      - spherity_coding_challenge_network
  frontend:
    build:
      context: ./
      target: frontend-dev
    container_name: spherity_coding_challenge_frontend
    develop:
      watch:
        - path: ./frontend/package.json
          action: restart
    volumes:
      - ./frontend:/usr/local/app
    ports:
      - 3001:3001
    networks:
      - spherity_coding_challenge_network

networks:
  spherity_coding_challenge_network:
    driver: bridge
