// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  DeleteCredentialData,
  DeleteCredentialResponses,
  GetAllCredentialsData,
  GetAllCredentialsResponses,
  GetCredentialData,
  GetCredentialResponses,
  GetIssuerData,
  GetIssuerResponses,
  GetKeyData,
  GetKeyResponses,
  IssueCredentialData,
  IssueCredentialResponses,
  ShareCredentialData,
  ShareCredentialResponses,
  VerifyCredentialData,
  VerifyCredentialResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get all the credentials stored in the backend
 */
export const getAllCredentials = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllCredentialsData, ThrowOnError>,
): RequestResult<GetAllCredentialsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetAllCredentialsResponses,
    unknown,
    ThrowOnError
  >({ url: '/api/credentials', ...options });

/**
 * Creates a new verifiable credential by signing the provided credential data and stores the result
 */
export const issueCredential = <ThrowOnError extends boolean = false>(
  options: Options<IssueCredentialData, ThrowOnError>,
): RequestResult<IssueCredentialResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    IssueCredentialResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/credentials',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Deletes the credential with the given id from the backend
 */
export const deleteCredential = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCredentialData, ThrowOnError>,
): RequestResult<DeleteCredentialResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteCredentialResponses,
    unknown,
    ThrowOnError
  >({ url: '/api/credentials/{id}', ...options });

/**
 * Returns the credential with the given id if it is stored in the backend
 */
export const getCredential = <ThrowOnError extends boolean = false>(
  options: Options<GetCredentialData, ThrowOnError>,
): RequestResult<GetCredentialResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<GetCredentialResponses, unknown, ThrowOnError>(
    { url: '/api/credentials/{id}', ...options },
  );

/**
 * Creates a derived credential from the credential with the given id (if it exists) that can the be shared with others
 */
export const shareCredential = <ThrowOnError extends boolean = false>(
  options: Options<ShareCredentialData, ThrowOnError>,
): RequestResult<ShareCredentialResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    ShareCredentialResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/credentials/{id}/share',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Verifies that the given credential string is a valid non-manipulated credential
 */
export const verifyCredential = <ThrowOnError extends boolean = false>(
  options: Options<VerifyCredentialData, ThrowOnError>,
): RequestResult<VerifyCredentialResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    VerifyCredentialResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/credentials/verification',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getIssuer = <ThrowOnError extends boolean = false>(
  options?: Options<GetIssuerData, ThrowOnError>,
): RequestResult<GetIssuerResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetIssuerResponses, unknown, ThrowOnError>({
    url: '/api/issuer',
    ...options,
  });

/**
 * Expose information about public keys that are required by verifiers that want to verify credentials issued by this wallet
 */
export const getKey = <ThrowOnError extends boolean = false>(
  options: Options<GetKeyData, ThrowOnError>,
): RequestResult<GetKeyResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<GetKeyResponses, unknown, ThrowOnError>({
    url: '/api/keys/{id}',
    ...options,
  });
