// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

export type VerifiableCredential = {
  proof: {
    id: string;
    type: string;
    created: string;
    verificationMethod: string;
    cryptoSuite: string;
    proofPurpose: string;
    proofValue: string;
  };
  '@context': Array<string>;
  /**
   * Unique identifier of the credential
   */
  id: string;
  /**
   * A concise human readable name for the credential
   */
  name?: string;
  /**
   * A human readable description for the credential
   */
  description?: string;
  type: Array<string>;
  /**
   * The entity that issued this credential
   */
  issuer: string;
  /**
   * The time at which this credential was issued',
   */
  issuanceDate: string;
  /**
   * The date and time after which the credentials starts being valid
   */
  validFrom?: string;
  /**
   * The date and time after which the credentials ceases to be valid
   */
  validUntil?: string;
  /**
   * A list of claims about the subject of this credential
   */
  credentialSubject: {
    [key: string]: unknown;
  };
};

export type CreateCredentialDto = {
  '@context': Array<string>;
  /**
   * A concise human readable name for the credential
   */
  name?: string;
  /**
   * A human readable description for the credential
   */
  description?: string;
  type: Array<string>;
  /**
   * The date and time after which the credentials starts being valid
   */
  validFrom?: string;
  /**
   * The date and time after which the credentials ceases to be valid
   */
  validUntil?: string;
  /**
   * A list of claims about the subject of this credential
   */
  credentialSubject: {
    [key: string]: unknown;
  };
};

export type GetAllCredentialsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/credentials';
};

export type GetAllCredentialsResponses = {
  200: Array<VerifiableCredential>;
};

export type GetAllCredentialsResponse =
  GetAllCredentialsResponses[keyof GetAllCredentialsResponses];

export type IssueCredentialData = {
  body: CreateCredentialDto;
  path?: never;
  query?: never;
  url: '/api/credentials';
};

export type IssueCredentialResponses = {
  201: VerifiableCredential;
};

export type IssueCredentialResponse =
  IssueCredentialResponses[keyof IssueCredentialResponses];

export type DeleteCredentialData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/credentials/{id}';
};

export type DeleteCredentialResponses = {
  200: unknown;
};

export type GetCredentialData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/credentials/{id}';
};

export type GetCredentialResponses = {
  200: VerifiableCredential;
};

export type GetCredentialResponse =
  GetCredentialResponses[keyof GetCredentialResponses];

export type ShareCredentialData = {
  body: Array<string>;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/credentials/{id}/share';
};

export type ShareCredentialResponses = {
  201: VerifiableCredential;
};

export type ShareCredentialResponse =
  ShareCredentialResponses[keyof ShareCredentialResponses];

export type VerifyCredentialData = {
  body: VerifiableCredential;
  path?: never;
  query?: never;
  url: '/api/credentials/verification';
};

export type VerifyCredentialResponses = {
  201: {
    [key: string]: unknown;
  };
};

export type VerifyCredentialResponse =
  VerifyCredentialResponses[keyof VerifyCredentialResponses];

export type GetIssuerData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/issuer';
};

export type GetIssuerResponses = {
  200: unknown;
};

export type GetKeyData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/keys/{id}';
};

export type GetKeyResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type GetKeyResponse = GetKeyResponses[keyof GetKeyResponses];
